### PR TITLE
Feat/install and style button

### PR DESCRIPTION
**Pull request by 0xRowdy**
installed button from https://ui.shadcn.com/docs/components/button
updated styles for button to match figma. Since we did not have design for all button variants I improvised following the pattern from replacing the other color values. I will follow up with Chiali to review and confirm.

Note: the primary button background is vd-text-blue. using this var as the background could be confusing.

Screenshot 2024-01-25 at 3 43 20 PM

### CODE REVIEW

**Comment by thebeyondr** [comment]
> Note: the primary button background is vd-text-blue. using this var as the background could be confusing.

@CJ-Rose can we update the token to be something else? I'd prefer if colors were named neutrally (not text or component based)

**Review by thebeyondr — COMMENTED** [review]
> Note: the primary button background is vd-text-blue. using this var as the background could be confusing.

@CJ-Rose can we update the token to be something else? I'd prefer if colors were named neutrally (not text or component based)

**Review by CJ-Rose — COMMENTED** [review]
> > Note: the primary button background is vd-text-blue. using this var as the background could be confusing.
> 
> @CJ-Rose can we update the token to be something else? I'd prefer if colors were named neutrally (not text or component based)

yep. originally i gave them different names bc the text color is "Cloud burst" while the accents are all named as degrees of "Gothic" in the figma. but since the darkest "Gothic" shade being used is 700, i think its fine to change `vd-text-blue` to `vd-blue-900`

**Comment by 0xRowdy** [comment]
> > > Note: the primary button background is vd-text-blue. using this var as the background could be confusing.
> > 
> > 
> > @CJ-Rose can we update the token to be something else? I'd prefer if colors were named neutrally (not text or component based)
> 
> yep. originally i gave them different names bc the text color is "Cloud burst" while the accents are all named as degrees of "Gothic" in the figma. but since the darkest "Gothic" shade being used is 700, i think its fine to change `vd-text-blue` to `vd-blue-900`

Sounds good. I'm happy to make that change in this PR.

**Review by CJ-Rose — APPROVED** [review]

**Pull request merged**
