### PR TITLE
Feat/global footer

### PR DESCRIPTION
**Pull request by 0xRowdy**
Created mobile and desktop variants of the global footer.

Screenshot 2024-02-06 at 9 51 15 AM
Screenshot 2024-02-06 at 9 52 13 AM
Screenshot 2024-02-06 at 9 52 18 AM

### CODE REVIEW

**Comment by 0xRowdy** [comment]
Note: I pulled in the global-nav to gain access to the logo asset.

**Comment by CJ-Rose** [comment]
@0xRowdy is this one ready to review?

**Comment by 0xRowdy** [comment]
> @0xRowdy is this one ready to review?

Yeah, but it has the stuff for the header in it so it looks larger than it is.

**Review by CJ-Rose — APPROVED** [review]
lgtm 🚀

**Comment by thebeyondr** [comment]
guys how did this merge when my terminal was yelling at me about missing `key` props? (Fixed in #25 )
image

**Pull request merged**
